/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class life_nuggets_rs_Bbs */

#ifndef _Included_life_nuggets_rs_Bbs
#define _Included_life_nuggets_rs_Bbs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     life_nuggets_rs_Bbs
 * Method:    bbs_blind_signature_commitment
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_life_nuggets_rs_Bbs_bbs_1blind_1signature_1commitment
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     life_nuggets_rs_Bbs
 * Method:    bbs_verify_blind_signature_proof
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_life_nuggets_rs_Bbs_bbs_1verify_1blind_1signature_1proof
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     life_nuggets_rs_Bbs
 * Method:    bbs_blind_sign
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_life_nuggets_rs_Bbs_bbs_1blind_1sign
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     life_nuggets_rs_Bbs
 * Method:    bbs_get_unblinded_signature
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_life_nuggets_rs_Bbs_bbs_1get_1unblinded_1signature
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     life_nuggets_rs_Bbs
 * Method:    bbs_verify
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_life_nuggets_rs_Bbs_bbs_1verify
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
